"""empty message

Revision ID: 07616f812796
Revises: 7a5ab2045b41
Create Date: 2023-12-12 11:10:13.258442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07616f812796'
down_revision = '7a5ab2045b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salary_hour', sa.Double(), nullable=False))
        batch_op.add_column(sa.Column('rating', sa.Double(), nullable=True))

    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('persons', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('salary_hour')

    # ### end Alembic commands ###
